repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: detect-private-key
      - id: end-of-file-fixer

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        files: \.(js|css|yaml)$
        exclude: "(bootstrap)"
        args:
          - "--tab-width"
          - "4"

  - repo: https://github.com/thibaudcolas/curlylint
    rev: "v0.13.1"
    hooks:
      - id: curlylint
        files: \.(html|j2)$
        exclude: ^theme/.not_used/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.7
    hooks:
      - id: ruff
        args: [ --fix ]
        types_or: [ python, pyi ]
      - id: ruff-format
        types_or: [ python, pyi ]


  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.13
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-ruff
          - ruff
