[tool.poetry]
name = "kanguros-blog"
version = "kanguros.github.io"
description = ""
authors = ["Kamil Urbanek <urbanek.kamil@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pelican = { extras = ["markdown"], version = "^4.8.0" }
typogrify = "^2.0.7"
pymdown-extensions = "^10"
invoke = "2.1.0"
livereload = "2.6.3"

[tool.poetry.dev-dependencies]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
