[tool.poetry]
name = "kanguros.github.io"
version = "0.2.0"
description = ""
authors = ["Kamil Urbanek <urbanek.kamil@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8.1"
pelican = { extras = ["markdown"], version = "^4.8.0" }
typogrify = "^2.0.7"
pymdown-extensions = "^10"
invoke = "^2.1"
livereload = "^2.6.0"
pymarkdownlnt = "^0.9.11"
#pyreveal = {path = "pyreveal"}
pelican-yaml-metadata = "^2.1.1"
pelican-similar-posts = "^1.0.0"
pelican-neighbors = "^1.2.0"
pelican-sitemap = "^1.1.0"
pelican-readtime = "^0.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
