name: Generate and deploy website
on:
  push:
    branches:
      - master


jobs:
  build_job:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Checkout master branch
        id: checkout-master
        uses: actions/checkout@v2
      - name: Install poetry
        run: |
          pip install -v poetry
      - name: Install site dependencies
        run: |
          poetry install -vv
      - name: Generate site
        id: run-pelican
        run: |
          poetry run pelican content --output output --settings publishconf.py
      - name: Push to GHPage
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: deploy
          publish_dir: ./output
          user_name: 'deploy-bot'
          user_email: 'deploy-bot@noreply.github.io'
      - name: Notice
        if: ${{ success() }}
        run: |
          echo '::notice:: Site deployed.'
