name: Generate and deploy website
on:
  push:
    branches:
      - master


jobs:
  build_job:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Checkout master branch
        id: checkout-master
        uses: actions/checkout@v2
#      - name: Cache dependencies
#        uses: actions/cache@v2
#        with:
#          path: ~/.cache/pip
##          path: ~/.cache/pypoetry/virtualenvs
#          key: pelican-4.8.0-${{ hashFiles('poetry.lock') }}
#          restore-keys: |
#            pelican-4.8.0-
      - name: Install poetry
#        if: ${{ failure() }}
        run: |
          pip install -v poetry
      - name: Cache site dependencies
        uses: actions/cache@v2
        continue-on-error: true
        with:
          fail-on-cache-miss: true
          path: ~/.cache/pypoetry/virtualenvs
          key: website-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            website-
      - name: Install site dependencies
        if: ${{ failure() }}
        run: |
          poetry install -vv
      - name: Generate site
        id: run-pelican
        run: |
          poetry run pelican content --output output --settings publishconf.py
      - name: Push to GHPage
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: deploy
          publish_dir: ./output
          user_name: 'deploy-bot'
          user_email: 'deploy-bot@noreply.github.io'
      - name: Notice
        if: ${{ success() }}
        run: |
          echo '::notice:: Site deployed.'
      - name: Failed
        if: ${{ failure() }}
        run: |
          echo '::error:: Deploy failed.'

