name: Generate and deploy website

on:
  push:
    branches:
      - master


jobs:
  build_job:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        id: checkout-master
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Mermaid CLI
        run: npm install -g @mermaid-js/mermaid-cli

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install poetry
        run: |
          pip install -v poetry

      - name: Install site dependencies
        run: |
          poetry install -vv --no-root

      - name: Generate site
        id: run-pelican
        run: |
          poetry run pelican content --output output --settings publishconf.py --fatal errors
      - name: Push to GHPage
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: deploy
          publish_dir: ./output
          user_name: 'deploy-bot'
          user_email: 'deploy-bot@noreply.github.io'

      - name: Notice
        if: ${{ success() }}
        run: |
          echo '::notice:: Site deployed.'
